In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
dataset=pd.read_csv('heart_.csv')
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [9]:
x_train

array([[62.,  0.,  0., ...,  0.,  2.,  2.],
       [40.,  1.,  3., ...,  2.,  0.,  3.],
       [54.,  0.,  2., ...,  2.,  0.,  2.],
       ...,
       [57.,  1.,  0., ...,  1.,  0.,  1.],
       [70.,  1.,  0., ...,  1.,  3.,  2.],
       [48.,  1.,  0., ...,  2.,  0.,  2.]])

In [11]:
y_train

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1],
      dtype=int64)

In [13]:
x_test

array([[6.90e+01, 1.00e+00, 3.00e+00, 1.60e+02, 2.34e+02, 1.00e+00,
        0.00e+00, 1.31e+02, 0.00e+00, 1.00e-01, 1.00e+00, 1.00e+00,
        2.00e+00],
       [6.00e+01, 1.00e+00, 0.00e+00, 1.25e+02, 2.58e+02, 0.00e+00,
        0.00e+00, 1.41e+02, 1.00e+00, 2.80e+00, 1.00e+00, 1.00e+00,
        3.00e+00],
       [5.10e+01, 1.00e+00, 0.00e+00, 1.40e+02, 2.61e+02, 0.00e+00,
        0.00e+00, 1.86e+02, 1.00e+00, 0.00e+00, 2.00e+00, 0.00e+00,
        2.00e+00],
       [5.70e+01, 0.00e+00, 0.00e+00, 1.40e+02, 2.41e+02, 0.00e+00,
        1.00e+00, 1.23e+02, 1.00e+00, 2.00e-01, 1.00e+00, 0.00e+00,
        3.00e+00],
       [5.60e+01, 1.00e+00, 0.00e+00, 1.25e+02, 2.49e+02, 1.00e+00,
        0.00e+00, 1.44e+02, 1.00e+00, 1.20e+00, 1.00e+00, 1.00e+00,
        2.00e+00],
       [5.70e+01, 1.00e+00, 0.00e+00, 1.65e+02, 2.89e+02, 1.00e+00,
        0.00e+00, 1.24e+02, 0.00e+00, 1.00e+00, 1.00e+00, 3.00e+00,
        3.00e+00],
       [5.40e+01, 1.00e+00, 0.00e+00, 1.24e+02, 2.66e+02, 0.00e+00,
  

In [15]:
y_test

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1], dtype=int64)

In [17]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()
x_train=sc.fit_transform(x_train)  #xscaled=x-mean/std: to make the data optimised or standardised
x_test=sc.transform(x_test)

In [19]:
x_train

array([[ 0.84922243, -1.46385011, -0.93695994, ..., -2.29292574,
         1.28737554, -0.48665585],
       [-1.54424513,  0.68313005,  1.97001833, ...,  0.93316745,
        -0.67202623,  1.12664163],
       [-0.02112941, -1.46385011,  1.00102558, ...,  0.93316745,
        -0.67202623, -0.48665585],
       ...,
       [ 0.30525253,  0.68313005, -0.93695994, ..., -0.67987914,
        -0.67202623, -2.09995333],
       [ 1.71957427,  0.68313005, -0.93695994, ..., -0.67987914,
         2.26707642, -0.48665585],
       [-0.67389329,  0.68313005, -0.93695994, ...,  0.93316745,
        -0.67202623, -0.48665585]])

In [21]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)

LogisticRegression()

In [23]:
y_pred=classifier.predict(x_test)
df=pd.DataFrame(y_pred,y_test)
df

0
1   1
0   0
1   0
0   0
0   0
.. ..
0   1
0   0
1   1
0   0
1   1

[61 rows x 1 columns]

In [27]:
classifier.predict(sc.transform([[63,	1,	3,	145,	233,	1,	0,	150,	0,	2.3,	0,	0,	1]]))

array([1], dtype=int64)

In [29]:
classifier.predict(sc.transform([[57,	0,	0,	120,	354,	0,	1,	163,	1,	0.6,	2,	0,	2	]]))

array([1], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

accuracy=accuracy_score(y_test,y_pred)
print("Accuracy",accuracy)

precision=precision_score(y_test,y_pred)
print("Precision",precision)

recall=recall_score(y_test,y_pred)
print("Recall",recall)

[[27  5]
 [ 5 24]]
Accuracy 0.8360655737704918
Precision 0.8275862068965517
Recall 0.8275862068965517


In [33]:
classifier.predict(sc.transform([[41,0,	1,	130,	204,	0,	0,	172,	0,	1.4,	2,	0,	2	]]))

array([1], dtype=int64)